name: API Tests with Newman postman
on:
  schedule:
    - cron: '30 6 * * *'
  push:
    branches: [ main, master, feature ]
  pull_request:
    branches: [ main, master, feature ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Install Newman HTML Reporter
        # Ensure the html reporter is available for Newman.
        run: npm install newman-reporter-html

      - name: Create test-results directory
        run: mkdir -p ./test-results/api-test-results

      - name: Run API tests
        run: |
          newman run universities-collection.json -r html,junit \
            --reporter-html-export test-results/api-test-results/results.html \
            --reporter-junit-export test-results/api-test-results/results.xml

      - name: Debug - List files in test-results
        run: ls -R ./test-results

      - name: Upload API Test Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: api-test-report
          path: ./test-results/api-test-results
          retention-days: 30
